### ISSUE TITLE
lack of time symmetry in run_mmp when creating messages

### ISSUE THREAD

**Issue by Arun-Niranjan** [infer-actively/pymdp#22]
When going through [mmp ](https://github.com/infer-actively/pymdp/blob/master/pymdp/core/algos/mmp.py)with @conorheins yesterday, I noticed this section:

```
                # past message
                if t == 0:
                    lnB_past = spm_log(prior[f])
                else:
                    past_msg = B[f][:, :, int(policy[t - 1, f])].dot(qs_seq[t - 1][f])
                    lnB_past = spm_log(past_msg)

                # future message
                if t >= future_cutoff:
                    lnB_future = qs_T[f]
                else:
                    future_msg = trans_B[f][:, :, int(policy[t, f])].dot(qs_seq[t + 1][f])
                    lnB_future = spm_log(future_msg)
```

I am not sure if the `past_msg `and `future_msg `lines are consistent with their use of `t-1`, `t` and `t +1`. I think this is worth checking against 1) the original SPM to see what they do and 2)  deciding what the correct behaviour should be.

**Comment by conorheins** [comment]
In terms of the testing against the SPM, it has been tested (see the file `test_mmp.py`, where it's tested against several different 'edge cases' of MMP), so it's giving the same outputs as how MMP is implemented in SPM_MDP_VB_X.

But I share your initial hunch about these index operations being strange/counter-intuitive. However, thinking more about actions (encoded as `policy[t,f]`), I now understand why this indexing actually makes sense. Actions at time `t` link (beliefs about) states at that time `t` to (beliefs about) states at the next timestep `t+1`. If we're considering some 'current' timestep `t` ('current' relative to the loop from `range(0,infer_len)`), then beliefs at time `t` should be getting messages from beliefs at time `t-1` and beliefs at time `t+1`. The action linking beliefs from t-1 to t is `policy[t-1,f]` (i.e. the action at time `t-1`), and the actions linking beliefs from t to t+1 is `policy[t,f]`. So these policy indices make sense. The action always links one timestep to the next. If we used `policy[t+1,f]` to get the future message, that wouldn't make sense -- since that would be the action that links `qs_seq[t+1]` to `qs_seq[t+2]`. Whereas we want the action that links t to t+1. 

Does that make sense?

**Comment by Arun-Niranjan** [comment]
Thanks @conorheins - yes the concept that the beliefs themselves and beliefs resulting from a policy have staggered indexes clears this up
