### ISSUE TITLE
Error happend when using update_B()

### ISSUE THREAD

**Issue by xugami** [infer-actively/pymdp#91]
It showed some error during runing update_B()
![image](https://user-images.githubusercontent.com/27820981/185345147-6a96f412-9854-4644-9f34-c9c5636d6a6c.png)

**Comment by conorheins** [comment]
Hi @xugami -- which version of `pymdp` are you using? It seems like you might be using v0.0.3 or v0.0.4.

This error has been fixed in the latest release (see [here](https://github.com/infer-actively/pymdp/releases/tag/v0.0.5)).

If my suspicion is correct, then you should be able to fix this by upgrading your version of `pymdp`:

```
pip install --upgrade inferactively-pymdp
```

Alternatively, you can install the dev verison of `pymdp`, instructions for which can be found [here](https://github.com/infer-actively/pymdp#Contributing).

**Comment by xugami** [comment]
Thanks , this problem has been fixed by upgrading from v0.0.4 to  v0.0.5.
